### ISSUE TITLE
Base URL is not reflected in the link address of [View/Download] button

### ISSUE THREAD

**Issue by magichan-lab** [YoshinoriN/gitbucket-application-logs-plugin#24]
I set the base URL to "http://(IP address)/gitbucket" in the system settings.
In that case, I expected that the link address of the "view button" would be "http://(IP address)/gitbukcket/admin/application-logs/1/view", but  actually it was "http://(IP address)/admin/Application-logs/1/view".

GITBUCKET_VERSION : 4.32.0
Application-logs VERSION : 2.0.0

**Comment by yoshinorin** [comment]
@magichan-lab 

Sorry, so very late reply.
This issue fixed in `v3.1.0`.

> https://github.com/yoshinorin/gitbucket-application-logs-plugin/releases/tag/v3.1.0

Thank you
